apiVersion: v1
kind: Service
metadata:
  name: ctfd-mysql
  labels:
    app: ctfd
spec:
  ports:
    - port: 3306
  selector:
    app: ctfd
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: ctfd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ctfd-mysql
  labels:
    app: ctfd
spec:
  selector:
    matchLabels:
      app: ctfd
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ctfd
        tier: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: ctfd
        - name: MYSQL_USER
          value: ctfd
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
                name: mysql-pass
                key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim